### ISSUE TITLE
Uncaught Error: Class 'WireDatabaseBackup'

### ISSUE THREAD

**Issue by jlahijani** [wireshell/wireshell#46]
Running the 'wireshell new' command on PW 3.0.16 and PHP 7.

```
PHP Fatal error:  Uncaught Error: Class 'WireDatabaseBackup' not found in /home/vagrant/.composer/vendor/wireshell/wireshell/src/Helpers/Installer.php:486
Stack trace:
#0 /home/vagrant/.composer/vendor/wireshell/wireshell/src/Helpers/Installer.php(391): Wireshell\Helpers\Installer->profileImportSQL(Object(PDO), '/home/vagrant/x...', '/home/vagrant/x...')
#1 /home/vagrant/.composer/vendor/wireshell/wireshell/src/Helpers/Installer.php(303): Wireshell\Helpers\Installer->profileImport(Object(PDO))
#2 /home/vagrant/.composer/vendor/wireshell/wireshell/src/Commands/Common/NewCommand.php(564): Wireshell\Helpers\Installer->dbSaveConfig(Array, Array)
#3 /home/vagrant/.composer/vendor/wireshell/wireshell/src/Commands/Common/NewCommand.php(274): Wireshell\Commands\Common\NewCommand->installProcessWire(Array, Array)
#4 /home/vagrant/.composer/vendor/symfony/console/Command/Command.php(259): Wireshell\Commands\Common\NewCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput in /home/vagrant/.composer/vendor/wireshell/wireshell/src/Helpers/Installer.php on line 486
```

**Comment by justonestep** [comment]
Hi,

assuming you're using the latest master branch, this can't work. 

[Related Post](https://processwire.com/talk/topic/9494-wireshell-an-extendable-processwire-command-line-interface/?p=118441):

> I'm in the process of getting wireshell PW3 ready. But I think it could use a bit more testing before I'll finally push it into the master branch. So I started a RC branch just for this purpose. If someone wanted to try and test it – which I would really appreciate: checkout branch feature/devns!

One more hint: I didn't test wireshell using PHP7, it definitely supports PHP56.

**Comment by hanthethanh** [comment]
I am having a similar problem:

```
[2016-08-15 03:54:45] name.INFO: Renamed /site-default => /site [] []
[2016-08-15 03:54:45] name.INFO: PHP version 5.6.24-0+deb8u1 [] []
[2016-08-15 03:54:45] name.INFO: PDO (mysql) database [] []
[2016-08-15 03:54:45] name.INFO: Filter functions (filter_var) [] []
[2016-08-15 03:54:45] name.INFO: MySQLi (not required by core, but may be required by some 3rd party modules) [] []
[2016-08-15 03:54:45] name.INFO: GD 2.0 or newer [] []
[2016-08-15 03:54:45] name.INFO: JSON support [] []
[2016-08-15 03:54:45] name.INFO: PCRE support [] []
[2016-08-15 03:54:45] name.INFO: CTYPE support [] []
[2016-08-15 03:54:45] name.INFO: ICONV support [] []
[2016-08-15 03:54:45] name.INFO: SESSION support [] []
[2016-08-15 03:54:45] name.INFO: HASH support [] []
[2016-08-15 03:54:45] name.INFO: SPL support [] []
[2016-08-15 03:54:45] name.INFO: /srv/pw_default2/site/assets/ is writable [] []
[2016-08-15 03:54:45] name.INFO: /srv/pw_default2/site/config.php is writable [] []
[2016-08-15 03:54:45] name.INFO: Installed .htaccess [] []
Please enter the timezone : UTC
[2016-08-15 04:06:20] name.INFO: Database connection successful to pw_db_default [] []
[2016-08-15 04:06:20] name.INFO: Saved configuration to ./site/config.php [] []
PHP Fatal error:  Class 'WireDatabaseBackup' not found in /home/thanh/.composer/vendor/wireshell/wireshell/src/Helpers/Installer.php on line 486

```

my environment:
```
$ php --version 
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

$ which composer
/usr/local/bin/composer

$ composer -V
Composer version 1.2.0 2016-07-19 01:28:52

$ which wireshell
/home/thanh/.composer/vendor/bin/wireshell

$ wireshell --version
wireshell - An extendable ProcessWire CLI version 0.6.0

```

Any hint please?

**Comment by marcus-herrmann** [comment]
Try if `$ composer dump-autoload` helps

**Comment by hanthethanh** [comment]
thanks for the prompt reply. 

I have run `composer global dump-autoload` and rerun the installation, but it didn't help. Same error again.

BTW,  I am on a slow internet connection and it takes very long to download pw. Is there any workaround for it, like using a pre-downloaded pw zip instead of downloading it?

**Comment by justonestep** [comment]
@hanthethanh 
You're using wireshell version 0.6.0, this is the stable master version compatible with PW 2.7.
But I guess you want to install the latest devns version (PW 3.0.29 atm). Therefore you have to checkout branch `feature/devns` as explained above (`wireshell --version` must return **wireshell - An extendable ProcessWire CLI version 1.0.0**).

Pointing to a pre-downloaded pw zip is not supported at the moment. Feel free to open an issue containing a feature request :)

**Comment by hanthethanh** [comment]
thank you for the hint, it helped.
